<a href="https://colab.research.google.com/github/deric0118/Data_Science_Tutorial3/blob/main/Data_Science_Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array=np.array([[None,None],[None,None]])
print(array)
print("Q1"+"\n")

[[None None]
 [None None]]
Q1



In [3]:
array2=np.random.randint(10,size=(3,4))
print(array2)
print("Q2"+"\n")

[[9 9 5 7]
 [5 3 4 8]
 [0 2 9 0]]
Q2



In [4]:
array3a=np.ones((2,2))
print(array3a)

[[1. 1.]
 [1. 1.]]


In [5]:
array3b=np.zeros((2,2))
print(array3b)
print("Q3"+"\n")

[[0. 0.]
 [0. 0.]]
Q3



In [6]:
array4=np.random.randint(10,size=(6,3))
array4_transpose=array4.transpose()
print(array4)
print(array4_transpose)
print("Q4"+"\n")

[[2 5 9]
 [9 4 9]
 [9 6 7]
 [4 0 5]
 [1 5 2]
 [8 7 3]]
[[2 9 9 4 1 8]
 [5 4 6 0 5 7]
 [9 9 7 5 2 3]]
Q4



In [7]:
array5a=np.random.randint(10,size=(2,3))
array5b=np.random.randint(10,size=(3,4))
dot5=np.dot(array5a,array5b)
print(dot5)
print("Q5"+"\n")


[[ 29  18  67  72]
 [ 36  64 106  74]]
Q5

